// 50 bộ thủ tiếng Trung phổ biến nhất
export const CHINESE_RADICALS = [
    { id: 1, radical: '人', name_vi: 'Nhân', pinyin: 'rén', meaning: 'Người', strokes: 2, examples: ['你', '他', '们'] },
    { id: 2, radical: '口', name_vi: 'Khẩu', pinyin: 'kǒu', meaning: 'Miệng', strokes: 3, examples: ['吃', '喝', '叫'] },
    { id: 3, radical: '手', name_vi: 'Thủ', pinyin: 'shǒu', meaning: 'Tay', strokes: 4, examples: ['打', '拿', '捉'] },
    { id: 4, radical: '心', name_vi: 'Tâm', pinyin: 'xīn', meaning: 'Tim/Lòng', strokes: 4, examples: ['想', '思', '忘'] },
    { id: 5, radical: '水', name_vi: 'Thủy', pinyin: 'shuǐ', meaning: 'Nước', strokes: 4, examples: ['河', '海', '洗'] },
    { id: 6, radical: '火', name_vi: 'Hỏa', pinyin: 'huǒ', meaning: 'Lửa', strokes: 4, examples: ['烧', '炒', '灯'] },
    { id: 7, radical: '木', name_vi: 'Mộc', pinyin: 'mù', meaning: 'Gỗ/Cây', strokes: 4, examples: ['树', '林', '森'] },
    { id: 8, radical: '金', name_vi: 'Kim', pinyin: 'jīn', meaning: 'Vàng/Kim loại', strokes: 8, examples: ['银', '铁', '钱'] },
    { id: 9, radical: '土', name_vi: 'Thổ', pinyin: 'tǔ', meaning: 'Đất', strokes: 3, examples: ['地', '城', '堂'] },
    { id: 10, radical: '日', name_vi: 'Nhật', pinyin: 'rì', meaning: 'Mặt trời/Ngày', strokes: 4, examples: ['明', '时', '早'] },
    { id: 11, radical: '月', name_vi: 'Nguyệt', pinyin: 'yuè', meaning: 'Mặt trăng/Tháng', strokes: 4, examples: ['明', '朋', '期'] },
    { id: 12, radical: '女', name_vi: 'Nữ', pinyin: 'nǚ', meaning: 'Nữ/Phụ nữ', strokes: 3, examples: ['妈', '姐', '好'] },
    { id: 13, radical: '子', name_vi: 'Tử', pinyin: 'zǐ', meaning: 'Con', strokes: 3, examples: ['学', '孩', '字'] },
    { id: 14, radical: '目', name_vi: 'Mục', pinyin: 'mù', meaning: 'Mắt', strokes: 5, examples: ['看', '眼', '睡'] },
    { id: 15, radical: '耳', name_vi: 'Nhĩ', pinyin: 'ěr', meaning: 'Tai', strokes: 6, examples: ['听', '闻', '聪'] },
    { id: 16, radical: '言', name_vi: 'Ngôn', pinyin: 'yán', meaning: 'Lời nói', strokes: 7, examples: ['说', '话', '语'] },
    { id: 17, radical: '足', name_vi: 'Túc', pinyin: 'zú', meaning: 'Chân', strokes: 7, examples: ['跑', '跳', '路'] },
    { id: 18, radical: '刀', name_vi: 'Đao', pinyin: 'dāo', meaning: 'Dao', strokes: 2, examples: ['切', '分', '刻'] },
    { id: 19, radical: '力', name_vi: 'Lực', pinyin: 'lì', meaning: 'Sức mạnh', strokes: 2, examples: ['动', '加', '助'] },
    { id: 20, radical: '山', name_vi: 'Sơn', pinyin: 'shān', meaning: 'Núi', strokes: 3, examples: ['岛', '岸', '崖'] },
    { id: 21, radical: '石', name_vi: 'Thạch', pinyin: 'shí', meaning: 'Đá', strokes: 5, examples: ['砖', '破', '碗'] },
    { id: 22, radical: '田', name_vi: 'Điền', pinyin: 'tián', meaning: 'Ruộng', strokes: 5, examples: ['男', '界', '留'] },
    { id: 23, radical: '禾', name_vi: 'Hòa', pinyin: 'hé', meaning: 'Lúa', strokes: 5, examples: ['种', '秋', '科'] },
    { id: 24, radical: '竹', name_vi: 'Trúc', pinyin: 'zhú', meaning: 'Tre', strokes: 6, examples: ['笔', '算', '筷'] },
    { id: 25, radical: '糸', name_vi: 'Mịch', pinyin: 'mì', meaning: 'Sợi tơ', strokes: 6, examples: ['红', '线', '绿'] },
    { id: 26, radical: '衣', name_vi: 'Y', pinyin: 'yī', meaning: 'Áo/Quần áo', strokes: 6, examples: ['被', '裤', '袋'] },
    { id: 27, radical: '食', name_vi: 'Thực', pinyin: 'shí', meaning: 'Thức ăn', strokes: 9, examples: ['饭', '饿', '饮'] },
    { id: 28, radical: '马', name_vi: 'Mã', pinyin: 'mǎ', meaning: 'Ngựa', strokes: 3, examples: ['骑', '驾', '驻'] },
    { id: 29, radical: '鸟', name_vi: 'Điểu', pinyin: 'niǎo', meaning: 'Chim', strokes: 5, examples: ['鸡', '鸭', '鹅'] },
    { id: 30, radical: '鱼', name_vi: 'Ngư', pinyin: 'yú', meaning: 'Cá', strokes: 8, examples: ['鲜', '鲤', '鲸'] },
    { id: 31, radical: '虫', name_vi: 'Trùng', pinyin: 'chóng', meaning: 'Sâu bọ', strokes: 6, examples: ['蛇', '蝴', '蚊'] },
    { id: 32, radical: '犬', name_vi: 'Khuyển', pinyin: 'quǎn', meaning: 'Chó', strokes: 4, examples: ['狗', '猫', '猪'] },
    { id: 33, radical: '贝', name_vi: 'Bối', pinyin: 'bèi', meaning: 'Vỏ sò/Tiền', strokes: 4, examples: ['财', '货', '贵'] },
    { id: 34, radical: '车', name_vi: 'Xa', pinyin: 'chē', meaning: 'Xe', strokes: 4, examples: ['轮', '转', '轻'] },
    { id: 35, radical: '门', name_vi: 'Môn', pinyin: 'mén', meaning: 'Cửa', strokes: 3, examples: ['开', '关', '间'] },
    { id: 36, radical: '雨', name_vi: 'Vũ', pinyin: 'yǔ', meaning: 'Mưa', strokes: 8, examples: ['雪', '雷', '霜'] },
    { id: 37, radical: '风', name_vi: 'Phong', pinyin: 'fēng', meaning: 'Gió', strokes: 4, examples: ['飘', '飞', '风'] },
    { id: 38, radical: '大', name_vi: 'Đại', pinyin: 'dà', meaning: 'Lớn', strokes: 3, examples: ['天', '太', '夫'] },
    { id: 39, radical: '小', name_vi: 'Tiểu', pinyin: 'xiǎo', meaning: 'Nhỏ', strokes: 3, examples: ['少', '尖', '尘'] },
    { id: 40, radical: '王', name_vi: 'Vương', pinyin: 'wáng', meaning: 'Vua/Ngọc', strokes: 4, examples: ['玩', '球', '理'] },
    { id: 41, radical: '艹', name_vi: 'Thảo', pinyin: 'cǎo', meaning: 'Cỏ', strokes: 3, examples: ['花', '草', '茶'] },
    { id: 42, radical: '宀', name_vi: 'Miên', pinyin: 'mián', meaning: 'Mái nhà', strokes: 3, examples: ['家', '安', '宝'] },
    { id: 43, radical: '广', name_vi: 'Nghiễm', pinyin: 'guǎng', meaning: 'Mái hiên', strokes: 3, examples: ['店', '床', '度'] },
    { id: 44, radical: '走', name_vi: 'Tẩu', pinyin: 'zǒu', meaning: 'Đi/Chạy', strokes: 7, examples: ['起', '越', '赶'] },
    { id: 45, radical: '辶', name_vi: 'Sước', pinyin: 'chuò', meaning: 'Bước đi', strokes: 3, examples: ['过', '远', '近'] },
    { id: 46, radical: '页', name_vi: 'Hiệt', pinyin: 'yè', meaning: 'Đầu/Trang', strokes: 6, examples: ['头', '题', '领'] },
    { id: 47, radical: '方', name_vi: 'Phương', pinyin: 'fāng', meaning: 'Vuông/Hướng', strokes: 4, examples: ['放', '旅', '族'] },
    { id: 48, radical: '白', name_vi: 'Bạch', pinyin: 'bái', meaning: 'Trắng', strokes: 5, examples: ['百', '的', '皮'] },
    { id: 49, radical: '寸', name_vi: 'Thốn', pinyin: 'cùn', meaning: 'Tấc', strokes: 3, examples: ['对', '寻', '导'] },
    { id: 50, radical: '立', name_vi: 'Lập', pinyin: 'lì', meaning: 'Đứng', strokes: 5, examples: ['站', '竞', '章'] },
];

export const TOTAL_RADICALS = CHINESE_RADICALS.length;
